### ISSUE TITLE
Software Serial not working. Be carefull with ESP8266 package's version

### ISSUE THREAD

**Issue by ortegafernando** [InfinityWorldHI/Biometric-attendance-system-V1.0#4]
Hi, I think that someone could find this usefull.

I have been getting problems with SoftwareSerial and ESP8266 package version. (i am using a wemos d1 mini board for test). Trying enroll sketch, It seems that it can detect the fingerprint sensor, but after that ... "comunication error"

Software Serial is NOT working with 2.5.1 package version.
I have read in severalweb pages that we have to use 2.4 packages.

I will try 2.5.2 package version and write down here.

Update: 2.5.2 also not working with Software Serial

**Comment by ortegafernando** [comment]
Hi, finally you need to use any esp8266 package ABOVE 2.4, I mean, you can use 2.3, but not 2.4

"you have to take into account that Arduino core for ESP8266 version 2.4 and later has troubles with Software Serial (check plerup/espsoftwareserial#63).
So you have to use version 2.3."

[https://github.com/plerup/espsoftwareserial/issues/63](https://github.com/plerup/espsoftwareserial/issues/63)

**Comment by InfinityWorldHI** [comment]
Exactly, that's right.
When I tried using SIM800L with NodeMCU I had a communication problem sometimes.
So I change the ESP8266 version to 2.4.2 and after that everything worked as it should.
On other hands, When I made the code for this project (fingerprint system), I tired many ESP8266 versions in order to check if the Software Serial library will work or not, so after testing these libraries I noticed that the code worked. but sometimes still there problems while using 2.5.0 version.
Anyway, There are two versions I will test them soon for the SIM800L and NodeMCU project to know which is the better library for that.

Thanks for your time and sharing your result.
